# Generated by Django 5.0.6 on 2025-02-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_app', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddata',
            name='blockNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='boiled_storage_root_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='cassava_anthractnose_disease_incidence_6_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='cassava_anthractnose_disease_incidence_9_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='cassava_anthractnose_disease_severity_6_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='cassava_anthractnose_disease_severity_9_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='cassava_bacterial_blight_incidence_3_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='cassava_bacterial_blight_incidence_6_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='cassava_bacterial_blight_severity_3_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='cassava_bacterial_blight_severity_6_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='cassava_green_mite_severity_first_evaluation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='cassava_green_mite_severity_second_evaluation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='cassava_mosaic_disease_incidence_1_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='cassava_mosaic_disease_incidence_3_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='cassava_mosaic_disease_incidence_6_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='cassava_mosaic_disease_severity_1_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='cassava_mosaic_disease_severity_3_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='cassava_mosaic_disease_severity_6_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='dry_matter_content_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='dry_matter_content_specific_gravity_method',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='ease_of_peeling_root_cortex_visual_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='entryType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='fieldSize',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='first_apical_branch_height_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='fresh_shoot_weight_kg_per_plot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='fresh_storage_root_weight_per_plot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='germplasmDbId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='germplasmName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='germplasmSynonyms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='harvestDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='harvest_index_variable',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='initial_vigor_assessment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='locationDbId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='locationName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='number_of_planted_stakes_per_plot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='observationLevel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='observationUnitDbId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='observationUnitName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='plant_architecture_visual_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='plant_stands_harvested_counting',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='plantingDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='plotLength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='plotNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='plotWidth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='poundability_assessment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='programDbId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='programDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='programName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='proportion_lodged_plants_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='replicate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='root_neck_length_visual_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='root_number_counting',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='rotted_storage_root_counting',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='specific_gravity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='sprout_count_nine_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='sprout_count_one_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='sprout_count_six_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='sprout_count_three_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='sprouting_proportion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='storage_root_cortex_color_visual_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='storage_root_periderm_color_visual_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='storage_root_pulp_color_visual_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='storage_root_shape_visual_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='storage_root_size_visual_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='studyDbId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='studyDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='studyDesign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='studyName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='studyYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='taste_of_boiled_root_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='top_yield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='total_carotenoid_chart_1_8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddata',
            name='total_carotenoid_iCheck_method',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
